"""Add clean_media_url to episode model

Revision ID: 204fc5330c86
Revises: 967459374b38
Create Date: 2025-03-02 05:17:24.850688

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '204fc5330c86'
down_revision = '967459374b38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('clean_media_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'clean_media_url')
    # ### end Alembic commands ###
