"""Initial migration

Revision ID: 001
Revises:
Create Date: 2024-03-02

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adsegment',
        sa.Column('start_time', sa.Integer(), nullable=False),
        sa.Column('end_time', sa.Integer(), nullable=False),
        sa.Column('segment_type', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('transcript', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('episode_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name=op.f('fk_adsegment_episode_id_episode')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_adsegment')),
    )
    op.create_table('feed',
        sa.Column('url', sa.String(length=2048), nullable=False),
        sa.Column('title', sa.String(length=512), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('language', sa.String(length=50), nullable=True),
        sa.Column('author', sa.String(length=512), nullable=True),
        sa.Column('image_url', sa.String(length=2048), nullable=True),
        sa.Column('website_url', sa.String(length=2048), nullable=True),
        sa.Column('last_fetched', sa.DateTime(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_feed')),
        sa.UniqueConstraint('url', name=op.f('uq_feed_url')),
    )
    op.create_index(op.f('ix_feed_url'), 'feed', ['url'], unique=True)
    op.create_table('episode',
        sa.Column('guid', sa.String(length=2048), nullable=False),
        sa.Column('title', sa.String(length=512), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('published_date', sa.DateTime(), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('media_url', sa.String(length=2048), nullable=False),
        sa.Column('media_type', sa.String(length=100), nullable=True),
        sa.Column('media_size', sa.Integer(), nullable=True),
        sa.Column('download_path', sa.String(length=1024), nullable=True),
        sa.Column('download_status', sa.String(length=20), nullable=False),
        sa.Column('download_date', sa.DateTime(), nullable=True),
        sa.Column('processed_path', sa.String(length=1024), nullable=True),
        sa.Column('processed_date', sa.DateTime(), nullable=True),
        sa.Column('original_duration', sa.Integer(), nullable=True),
        sa.Column('processed_duration', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('feed_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name=op.f('fk_episode_feed_id_feed')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_episode')),
        sa.UniqueConstraint('guid', name=op.f('uq_episode_guid')),
    )
    op.create_index(op.f('ix_episode_guid'), 'episode', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_guid'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_feed_url'), table_name='feed')
    op.drop_table('feed')
    op.drop_table('adsegment')
    # ### end Alembic commands ###
